knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
#here::i_am("1_code/THD/1_libraries_and_settings.R")
library(here)
library(MASS)
library(tidyverse)
library(codebook)
library(survey)
library(questionr)
library(srvyr)
#install.packages("remotes")
#remotes::install_github("carlganz/svrepmisc")
library(svrepmisc)
library(svyVGAM)
#library(apsrtable)
#library(stargazer)
#library(texreg)
#install.packages("devtools")
#devtools::install_github("pewresearch/pewmethods", build_vignettes = TRUE)
library(pewmethods)
library(ri2)
library(modelsummary)
library(DescTools)
library(effects)
library(renv)
ggplot2::theme_set(ggplot2::theme_bw())
here()
set.seed(98)
options("modelsummary_factory_default" = "kableExtra")

renv::restore()
#renv::update()
#renv::snapshot()
