---
title: "Initial Data Report"
output: html_document
date: "2025-02-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(tidyverse)

dt <- read_csv(here("3_cleaned_data", "ACNT_followup_joined_draft.csv"))

var_cont <- function(v, a1, a2, b1, b2) {
  a <- ggplot(dt, aes(x =  !!sym(v))) +
    geom_histogram() +
    geom_vline(xintercept = median(dt[, v][[1]], na.rm = T)) +
    annotate("text", label = paste("med", median(dt[, v][[1]], na.rm = T)), x = a1, y = b1) +
    annotate("text", label = paste("mean", mean(dt[, v][[1]], na.rm = T)), x = a2, y = b2)
  
  a
}
```

## Survey roll-off item non-response, attention, attrition, and weighting

```{r emails}
# Emails available
sum(!is.na(dt$email))
# past work is equal to length?
summary(as.factor(dt$past_work))
```
```{r treatment vars}
summary(as.factor(dt$treatment_full.x))
mean(dt$treatment_vid == 1) # how many shown a video
summary(as.factor(dt$treatment_vid_type)) # only those shown video, which one?
```
```{r treatment regressions}
mod1 <- lm(ehf_exist == "Yes" ~ treatment_bin, data = dt)
summary(mod1)

mod2 <- lm(ehf_exist != "No" ~ treatment_bin, data = dt)
summary(mod2)

mod3 <- lm(ehf_exist == "Yes" ~ treatment_bin*ehf_aware_pretr, data = dt)
summary(mod3)

mod4 <- lm(ehf_exist != "No" ~ treatment_bin*ehf_aware_pretr, data = dt)
summary(mod4)

mod5 <- lm(ehf_exist == "Yes" ~ treatment_bin, data = filter(dt, treatment_full.x != "vid0"))
summary(mod5)

mod6 <- lm(ehf_exist != "No" ~ treatment_bin, data = filter(dt, treatment_full.x != "vid0"))
summary(mod6)

mod7 <- lm(ehf_exist == "Yes" ~ treatment_bin, data = filter(dt, treatment_full.x != "ctrl"))
summary(mod7)

mod8 <- lm(ehf_exist != "No" ~ treatment_bin, data = filter(dt, treatment_full.x != "ctrl"))
summary(mod8)

```



## Item non-response and outlier data

```{r age and pph}
# How many age and hourly wage values have been changed/set to NA?
sum(is.na(dt$pph_clean))
sum(dt$pph_corrected, na.rm = T)

sum(is.na(dt$age))
sum(is.na(dt$age_clean))
sum(dt$age_corrected)

# Plots for the above
var_cont("age_clean", 50, 50, 10, 20)
var_cont("pph_clean", 5, 5, 100, 150)
```

## Quality and attention checks

```{r}
sum(dt$quality == "high")
```
## Weighting

```{r}
ggplot(dt, aes(x = rk_wgt_trim)) +
  geom_histogram(binwidth = 0.05)

unique(data.frame(dt$rk_age, dt$rk_educ, dt$rk_gender, dt$rk_wgt_og))

ggplot(dt, aes(x = rk_dei_trim)) +
  geom_histogram(binwidth = 0.05)
```

## Measurement

```{r ehf_hire}
summary(as.factor(dt$hire_benefits_emerg))
mean(dt$hire_benefits_emerg_num)
median(dt$hire_benefits_emerg_num)

dt %>%
  select(hire_benefits_pto_num:hire_benefits_tuition_num) %>%
  as.matrix %>%
  cor %>%
  as.data.frame %>%
  rownames_to_column(var = 'var1') %>%
  gather(var2, value, -var1) %>%
  filter(var1 == "hire_benefits_emerg_num")


mean(dt$ehf_hire_bin)

# Relative to other factors for getting a different job. num/sum(num)
var_cont("ehf_hire_relative", 1, 1, 10, 30)
```
```{r ehf_exist}
summary(as.factor(dt$ehf_exist)) # Post-treatment

ggplot(dt, aes(x = ehf_exist, fill = treatment_vid)) + #treatment and post-treatment ehf existance
  geom_bar()
```

```{r ehf_prior_knowledge}
summary(as.factor(dt$ehf_aware_pretr))

ggplot(dt, aes(x = ehf_aware_pretr, fill = ehf_exist)) + #pre-treatment and post-treatment ehf existance
  geom_bar()

cor(as.numeric(dt$ehf_aware_pretr), (dt$ehf_exist == "Yes")) # what is the correlation between knowing pre-treatment and post-treatment?
```
```{r qualifying emergency}
summary(as.factor(dt$emergency))
```
```{r known recipient}
summary(as.factor(dt$ehf_other_recip))
mean(dt$ehf_other_recip == "Yes", na.rm = T) # over those shown question
sum(dt$ehf_other_recip == "Yes", na.rm = T)/1078 # over total respondents
```
```{r applied themselves and delay}
summary(as.factor(dt$ehf_applied))
mean(dt$ehf_applied == "Yes", na.rm = T) # over those shown question
sum(dt$ehf_applied == "Yes", na.rm = T)/1078 # over total respondents

summary(as.factor(dt$ehf_delay))
mean(dt$ehf_delay_num, na.rm = T)
median(dt$ehf_delay_num, na.rm = T)
```
```{r received money}
summary(as.factor(dt$ehf_received))

var_cont("ehf_rec_amount", 200, 200, 10, 15)
```
```{r ehf donations}
summary(as.factor(dt$ehf_donation))
sum(dt$ehf_donation == "Yes", na.rm = T)/1078 # percentage over all respondents

var_cont("ehf_don_amount", 2000, 2000, 10, 15)
```
```{r loyalty to workers and company}
summary(as.factor(dt$wrk_loyal))
mean(dt$wrk_loyal_num) # 1 is max loyalty
median(dt$wrk_loyal_num)
mean(dt$wrk_loyal_bin) # 1 is loyal

summary(as.factor(dt$emp_loyal))
mean(dt$emp_loyal_num) # 1 is max loyalty
median(dt$emp_loyal_num)
mean(dt$emp_loyal_bin) # 1 is loyal
```
```{r recommend and new job search}
summary(as.factor(dt$emp_reco))
mean(dt$emp_reco_num) # 1 is max recommend
median(dt$emp_reco_num)
mean(dt$emp_reco_bin) # 1 is recommend

summary(dt$new_job)
mean(dt$new_job_num)
mean(dt$new_job_bin) # Somewhat or more likely
```
```{r unionization}
summary(as.factor(dt$union_vote))
mean(dt$union_vote_num) # 1 is max for the union
median(dt$union_vote_num)
mean(dt$union_vote_bin) # 1 is at least leaning towards union

var_cont("union_coworkers_6", 10, 10, 100, 120) # coworker lean for or against union

cor(dt$union_coworkers_6, dt$union_vote_num) # Negative correlation makes sense, since 0 is max for the union
```
```{r experience with social assistance}
mean(dt$unemp_benefits == "Yes")

summary(as.factor(dt$app_time_unemp))
mean(dt$app_time_unemp_num, na.rm = T)
median(dt$app_time_unemp_num, na.rm = T)

summary(as.factor(dt$delay_unemp))
mean(dt$delay_unemp_num, na.rm = T)
median(dt$delay_unemp_num, na.rm = T)

summary(as.factor(dt$other_welfare))
```
```{r social assistance attitudes}
dt %>%
  select(govt_responsib_elder_num:govt_responsib_hardship_num) %>%
  colMeans() # with 1 being maximum responsibility

dt %>%
  select(govt_responsib_elder_bin:govt_responsib_hardship_bin) %>%
  colMeans() # with 1 being at least some responsibility

```

```{r expense DV}
summary(as.factor(dt$emergency_expense))
mean(dt$emergency_expense_num) # 0 is certainly not
median(dt$emergency_expense_num)
mean(dt$emergency_expense_bin) # 1 is more likely than not
```
```{r willingness to donate at end of survey}
summary(as.factor(dt$donate))
```
```{r attachment index}
var_cont("attachment_index", .5, .5, 10, 20)
```
## Covariates

```{r race and gender}
mean(dt$nonwhite == 1)
mean(dt$male == 1)
```
```{r educ}
summary(as.factor(dt$ed))
mean(dt$college == T) # "some college" is assumed to not be completed college
```
```{r tenure}
mean(dt$tenure_num, na.rm = T)
median(dt$tenure_num, na.rm = T)
```
```{r pay type}
mean(dt$hourly == 1)
```
```{r employment status}
mean(dt$employ_status == "Regular full-time")
```
## Variables not in PAP

```{r elections, ideology, registration}
mean(dt$registered == "Yes") # registered to vote?

summary(as.factor(dt$ideology))
summary(as.factor(dt$ideology_answered)) # coded "haven't thought about it" as NA
mean(dt$ideology_conlib_num, na.rm = T) # using the above, conlib on a numerical scale. From 0 lib to 1 con

summary(as.factor(dt$vote_lik_post_elec)) # problematic factor
summary(as.factor(dt$vote_lik_fix)) # fixed factor
summary(dt$vote_lik_fix_flag) # vote likelihood fixed for these obs

# Reminder: if a person states who they voted for, then they are assigned that they definitely voted.
# If that is NA, then that they definitely did not.

summary(as.factor(dt$vote_pres_post_elec))
sum(!is.na(dt$vote_pres_post_elec) & dt$vote_pres_post_elec != "Did not vote for President")/1078 # turnout
```
```{r healthcare}
mean(dt$healthcare == T) # do they get healthcare through their jobs?
```
```{r other demographics}
mean(dt$rent == "Rent") # do they rent or own

mean(dt$practice_religion_bin) # percent practicing at all
mean(dt$practice_religion_num) # numerical, where 0 is never, 1 is once a week

mean(dt$income_num, na.rm = T) # NAs could be "don't want to answer" answers.
```
```{r where did they see the add}
summary(as.factor(dt$utm_campaign))
summary(as.factor(dt$utm_medium))
```


