knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(here)
library(texreg)
library(MASS)
library(tidyverse)
library(survey)
library(questionr)
library(lmtest)
library(cdlTools)
library(sandwich)
library(lme4)
library(srvyr)
#install.packages("remotes")
#remotes::install_github("carlganz/svrepmisc")
library(svrepmisc)
library(svyVGAM)
#install.packages("devtools")
#devtools::install_github("pewresearch/pewmethods", build_vignettes = TRUE)
#library(pewmethods)
library(ri2)
library(modelsummary)
library(car)
library(DescTools)
library(ggExtra)
library(effects)
library(readr)
library(openxlsx)
library(readxl)
library(renv)
library(qualtRics)
library(gridExtra)
library(codebook)
library(likert)
library(excluder)
library(naniar)
library(psych)
library(codebookr)
library(kableExtra)
library(RCT)
library(binom)
library(marginaleffects)
library(cobalt)
library(gtsummary)
library(interpretCI)
library(logistf)
library(pwr)
library(stargazer)
library(tidymodels)
ggplot2::theme_set(ggplot2::theme_bw(base_size = 13))
here()
set.seed(98)
options("modelsummary_factory_default" = "kableExtra")
#options(modelsummary_get = "all")

#renv::restore()
#renv::update()
#renv::snapshot()
